# Skrypt wczytujacy dane .xls i zapisujacy je w formie csv
(Wstępne czysczenie danych)

In [57]:
import pandas as pd


df = pd.read_excel("dane-zeliwo-ADI.xls",skiprows=12)

In [1]:
import pandas as pd

df = pd.read_excel("../data/Test SMAD.xlsx")

In [2]:
df.to_csv("test.csv")

,Nr źródła,C [%],Si [%],S [%],P [%],Mg [%],Mn [%],Ni [%],Cu [%],Mo [%],...,Unnamed: 32,Rm [MPa],"R0,2 [MPa]",A5 [%],Twardość Brinella [HB],Udarność Charpy [J],Temperatura pomiaru udarności [˚C],Martensite volume fraction Xα',Udział austenitu szczątkowego XγR,Zawartość węgla w austenicie
0,200,3.63,2.52,0.013,0.028,0.0043,0.162,0.024,0.215,0.002,...,NaN,921.0,NaN,5.3,323.0,NaN,NaN,NaN,17.6,NaN
1,200,3.63,2.52,0.013,0.028,0.0043,0.162,0.024,0.215,0.002,...,NaN,847.0,NaN,6.1,331.0,NaN,NaN,NaN,21.2,NaN
2,200,3.63,2.52,0.013,0.028,0.0043,0.162,0.024,0.215,0.002,...,NaN,812.0,NaN,7.4,319.0,NaN,NaN,NaN,25.4,NaN
3,200,3.63,2.52,0.013,0.028,0.0043,0.162,0.024,0.215,0.002,...,NaN,772.0,NaN,8.4,302.0,NaN,NaN,NaN,30.2,NaN
4,200,3.63,2.52,0.013,0.028,0.0043,0.162,0.024,0.215,0.002,...,NaN,952.0,NaN,5.1,325.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,x001,3.36,3.54,0.008,0.033,0.057,0.280,0.000,0.227,0.000,...,NaN,1571.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,x001,3.36,3.54,0.008,0.033,0.057,0.280,0.000,0.227,0.000,...,NaN,1273.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,x001,3.40,3.74,0.01,0.039,0.063,0.260,0.000,0.220,0.000,...,NaN,1514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,x001,3.40,3.74,0.01,0.039,0.063,0.260,0.000,0.220,0.000,...,NaN,1486.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,x001,3.40,3.74,0.01,0.039,0.063,0.260,0.000,0.220,0.000,...,NaN,1532.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df = df.iloc[:,10:57]

In [59]:
kolumny = [df.columns.str.findall('Unnamed')[i] != ['Unnamed'] for i in range(df.shape[1])]

In [60]:
df = df.loc[:,kolumny]

In [62]:
df.to_csv('dane-zeliwo.csv')

In [64]:
df2 = pd.read_csv('dane-zeliwo.csv',sep = ',')

In [65]:
df2.head()

,Unnamed: 0,Nr źródła,C [%],Si [%],S [%],P [%],Mg [%],Mn [%],Ni [%],Cu [%],...,A5 [%],Twardość Brinella [HB],Twardość Rockwella [HRC],Twardość Rockwella [HRA],Twardość Rockwella [HRB],Twardość Vickersa [HV],Udarność Charpy [J],Temperatura pomiaru udarności [˚C],Udział austenitu %,Martensite volume fraction Xα'
0,0,1,3.4,2.41,0.017,0.015,0.064,0.15,0.001,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.7,NaN
1,1,1,3.4,2.41,0.017,0.015,0.064,0.15,0.001,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.5,NaN
2,2,1,3.4,2.41,0.017,0.015,0.064,0.15,0.001,0.0,...,10.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.0,NaN
3,3,1,3.4,2.41,0.017,0.015,0.064,0.15,0.001,0.0,...,9.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.5,NaN
4,4,1,3.4,2.41,0.017,0.015,0.064,0.15,0.001,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.2,NaN